title: Giorgio Melloni
# description: code.projects.bioinfo.blog
show_downloads: false
google_analytics: UA-102057877-1

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - blog.md
  - projects.md
  - publications.md
  - about.md

github_username: gmelloni
linkedin_username: giorgio-melloni-bb51b26a
researchgate_username: Giorgio_Melloni
googlescholar_username: LSTvsNEAAAAJ&hl=en
